<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CIA.Contracts\CIA.Contracts.csproj" />
    <ProjectReference Include="..\CIA.Core\CIA.Core.csproj" />
  </ItemGroup>

</Project>
